import os
from accounts.models import Interest


def load_interests():
	interests = [
			"Artificial Intelligence",
			"Machine Learning",
			"Data Science",
			"Cybersecurity",
			"Web Development",
			"Mobile App Development",
			"Game Development",
			"Cloud Computing",
			"Big Data Analytics",
			"Computer Vision",
			"Natural Language Processing",
			"Robotics",
			"Augmented Reality (AR)",
			"Virtual Reality (VR)",
			"UI/UX Design",
			"Human-Computer Interaction",
			"Internet of Things (IoT)",
			"Blockchain Technology",
			"Cryptocurrency",
			"Computer Graphics",
			"Network Security",
			"Embedded Systems",
			"Bioinformatics",
			"Quantum Computing",
			"High-Performance Computing",
			"Computer Architecture",
			"Software Engineering",
			"Data Mining",
			"Information Retrieval",
			"Operating Systems",
			"Computer Networks",
			"Database Systems",
			"Compiler Design",
			"Computer Animation",
			"Wireless Communication",
			"Data Visualization",
			"Parallel Computing",
			"Natural Computing",
			"Cloud Security",
			"Fintech",
			"Ethical Hacking",
			"Digital Forensics",
			"Image Processing",
			"Computer Ethics",
			"Computational Biology",
			"Human-Robot Interaction",
			"Virtualization Technology",
			"Computer-Assisted Education",
	]

	interests_personal = [
			"Cooking",
			"Photography",
			"Painting",
			"Writing",
			"Reading",
			"Traveling",
			"Hiking",
			"Cycling",
			"Playing guitar",
			"Playing piano",
			"Dancing",
			"Yoga",
			"Meditation",
			"Running",
			"Swimming",
			"Soccer",
			"Basketball",
			"Tennis",
			"Volleyball",
			"Surfing",
			"Skiing",
			"Snowboarding",
			"Gaming",
			"Watching movies",
			"Listening to music",
			"Singing",
			"Crafting",
			"Gardening",
			"Birdwatching",
			"Astronomy",
			"Fashion",
			"Makeup",
			"DIY projects",
			"Pottery",
			"Woodworking",
			"Calligraphy",
			"Sculpting",
			"Collecting stamps",
			"Collecting coins",
			"Learning languages",
			"Volunteering",
			"Animal welfare",
			"Environmental conservation",
			"Wine tasting",
			"Coffee tasting",
			"Food blogging",
	]

	for interest in interests:
			print(interest)
			interest = Interest(name=interest, interest_type="C")
			interest.save()
			
	for interest in interests_personal:
			print(interest)
			interest = Interest(name=interest, interest_type="P")
			interest.save()