# Generated by Django 3.2.16 on 2023-02-18 17:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_auto_20230114_1405'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='bio',
            field=models.CharField(default='', max_length=500),
            preserve_default=False,
        ),
    ]
