# Generated by Django 3.2.19 on 2023-06-02 18:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0031_alter_workexperience_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='content',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
    ]
