# Generated by Django 3.2.19 on 2023-06-07 18:45

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0035_auto_20230607_1907'),
    ]

    operations = [
        migrations.CreateModel(
            name='CareerLevel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('level_type', models.CharField(choices=[('S', 'Student'), ('P', 'Professional')], max_length=1)),
            ],
        ),
        migrations.CreateModel(
            name='CareerPreferences',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('current_level', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='current_level_career_preferences', to='accounts.careerlevel')),
                ('looking_for', models.ManyToManyField(related_name='looking_for_career_preferences', to='accounts.CareerLevel')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='career_preferences', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
