# Generated by Django 3.2.18 on 2023-02-24 19:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recsys', '0004_alter_recommendation_recommended_on'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recommendation',
            name='recommended_on',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
