# Generated by Django 3.2.16 on 2023-01-13 16:37

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_customuser_likes'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='likes',
        ),
        migrations.AddField(
            model_name='customuser',
            name='likes',
            field=models.ManyToManyField(blank=True, related_name='_accounts_customuser_likes_+', to=settings.AUTH_USER_MODEL),
        ),
    ]
