# Generated by Django 3.2.18 on 2023-02-20 15:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0011_auto_20230220_1154'),
    ]

    operations = [
        migrations.AddField(
            model_name='language',
            name='icon_name',
            field=models.CharField(default='', max_length=255),
            preserve_default=False,
        ),
    ]
