# Generated by Django 3.2.18 on 2023-02-27 10:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0014_customuser_tfidf_input'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='type',
            field=models.CharField(choices=[('Student', 'Student'), ('Professional', 'Professional')], default='Student', max_length=255),
        ),
    ]
