# Generated by Django 3.2.18 on 2023-03-30 13:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0018_project_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='education',
            name='logo',
            field=models.ImageField(blank=True, null=True, upload_to='logos'),
        ),
    ]
