# Generated by Django 3.2.18 on 2023-03-30 13:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0019_education_logo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='education',
            name='logo',
        ),
        migrations.AddField(
            model_name='school',
            name='logo',
            field=models.ImageField(blank=True, null=True, upload_to='logos'),
        ),
    ]
