# Generated by Django 3.2.19 on 2023-05-28 13:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0025_alter_customuser_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='onboarded',
            field=models.BooleanField(default=False),
        ),
    ]
