# Generated by Django 3.2.19 on 2023-05-28 18:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0026_customuser_onboarded'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='image',
            field=models.ImageField(default='default-image.png', upload_to='profiles/'),
        ),
    ]
