# Generated by Django 3.2.19 on 2023-05-28 18:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0027_alter_customuser_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='image',
            field=models.ImageField(default='profiles/default-image.png', upload_to='profiles/'),
        ),
    ]
