# Generated by Django 3.2.19 on 2023-05-31 19:41

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0030_auto_20230531_2023'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workexperience',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='work_experiences', to=settings.AUTH_USER_MODEL),
        ),
    ]
