# Generated by Django 3.2.19 on 2023-06-07 18:07

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0034_question_useranswer'),
    ]

    operations = [
        migrations.AddField(
            model_name='interest',
            name='interest_type',
            field=models.CharField(choices=[('C', 'Career'), ('P', 'Personal')], default='', max_length=1),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='useranswer',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_answers', to=settings.AUTH_USER_MODEL),
        ),
    ]
