# Generated by Django 3.2.19 on 2023-06-07 22:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0037_auto_20230607_1956'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='current_level',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='current_level_users', to='accounts.careerlevel'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='looking_for',
            field=models.ManyToManyField(blank=True, null=True, related_name='looking_for_users', to='accounts.CareerLevel'),
        ),
    ]
