# Generated by Django 4.2.2 on 2023-06-12 13:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0039_projectanswer"),
    ]

    operations = [
        migrations.AlterField(
            model_name="customuser",
            name="bio",
            field=models.CharField(blank=True, default="", max_length=500, null=True),
        ),
    ]
