# Generated by Django 4.2.2 on 2023-06-12 13:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0041_alter_language_icon_name"),
    ]

    operations = [
        migrations.AddField(
            model_name="language",
            name="category",
            field=models.CharField(
                choices=[("L", "Language"), ("F", "Framework"), ("O", "Other")],
                default="O",
                max_length=1,
            ),
        ),
    ]
