# Generated by Django 4.2.2 on 2023-06-14 15:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0042_language_category"),
    ]

    operations = [
        migrations.AlterField(
            model_name="project",
            name="content",
            field=models.TextField(blank=True, null=True),
        ),
    ]
