# Generated by Django 4.2.2 on 2023-06-17 10:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0045_project_github_link_project_project_link_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="project", old_name="github_link", new_name="repo_link",
        ),
    ]
