# Generated by Django 4.2.2 on 2023-06-17 10:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0046_rename_github_link_project_repo_link"),
    ]

    operations = [
        migrations.AlterField(
            model_name="projectimage",
            name="project",
            field=models.ForeignKey(
                default=None,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="images",
                to="accounts.project",
            ),
        ),
    ]
