# Generated by Django 4.2.2 on 2023-06-17 13:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0047_alter_projectimage_project"),
    ]

    operations = [
        migrations.AddField(
            model_name="project",
            name="video_link",
            field=models.URLField(blank=True, null=True),
        ),
    ]
