# Generated by Django 4.2.2 on 2023-06-17 17:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0048_project_video_link"),
    ]

    operations = [
        migrations.RemoveField(model_name="project", name="content",),
        migrations.AlterField(
            model_name="project",
            name="description",
            field=models.TextField(blank=True, null=True),
        ),
    ]
