# Generated by Django 4.2.2 on 2023-06-19 14:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0050_alter_project_image"),
    ]

    operations = [
        migrations.AlterField(
            model_name="projectimage",
            name="project",
            field=models.ForeignKey(
                blank=True,
                default=None,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="images",
                to="accounts.project",
            ),
        ),
    ]
