# Generated by Django 4.2.2 on 2023-06-19 15:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0051_alter_projectimage_project"),
    ]

    operations = [
        migrations.AlterField(
            model_name="projectimage",
            name="image",
            field=models.ImageField(
                blank=True, null=True, upload_to="uploads/", verbose_name="Image"
            ),
        ),
    ]
