# Generated by Django 4.2.2 on 2023-06-20 16:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0052_alter_projectimage_image"),
    ]

    operations = [
        migrations.AddField(
            model_name="project",
            name="is_pinned",
            field=models.BooleanField(default=False),
        ),
    ]
