# Generated by Django 4.2.2 on 2023-06-27 10:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0053_project_is_pinned"),
    ]

    operations = [
        migrations.AddField(
            model_name="project",
            name="is_visible",
            field=models.BooleanField(default=True),
        ),
    ]
