# Generated by Django 4.2.2 on 2023-07-06 12:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0054_project_is_visible"),
    ]

    operations = [
        migrations.AlterField(
            model_name="education",
            name="description",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="workexperience",
            name="description",
            field=models.TextField(blank=True, null=True),
        ),
    ]
