# Generated by Django 4.2.2 on 2023-07-09 12:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0055_alter_education_description_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="careerlevel",
            name="level_type",
            field=models.CharField(
                choices=[("S", "Student"), ("P", "Professional"), ("R", "Recruiter")],
                max_length=1,
            ),
        ),
    ]
