# Generated by Django 4.2.2 on 2023-07-11 09:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0056_alter_careerlevel_level_type"),
    ]

    operations = [
        migrations.AlterField(
            model_name="customuser",
            name="current_level",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="current_level_users",
                to="accounts.careerlevel",
            ),
        ),
    ]
